# Generated by Django 3.2.4 on 2021-06-30 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_metrobus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrobusdata',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='geographic_point',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='id_alcaldia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulta_metrobus.alcaldia'),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='id_data',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='position_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='position_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='position_odometer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='position_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='trip_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='trip_route_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='trip_schedule_relationship',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='trip_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='vehicle_current_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='vehicle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrobusdata',
            name='vehicle_label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
