# Generated by Django 3.2.4 on 2021-06-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_metrobus', '0002_auto_20210630_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrobusdata',
            name='trip_start_date',
        ),
    ]
