# Generated by Django 3.2.4 on 2021-06-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_metrobus', '0003_remove_metrobusdata_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrobusdata',
            name='trip_start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
